name: Simple Cache Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Cache test data
      id: cache
      uses: actions/cache@v4
      with:
        path: ~/cache-test
        key: simple-test-v1
    
    - name: Install if no cache
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        echo "No cache - installing..."
        mkdir -p ~/cache-test
        echo "installed at $(date)" > ~/cache-test/install.txt
        echo "Done installing"
    
    - name: Use cached data
      run: |
        echo "Cache hit: ${{ steps.cache.outputs.cache-hit }}"
        ls -la ~/cache-test/
        cat ~/cache-test/install.txt
