name: LaTeX Compiler

on:
  push:
    paths: ['**.tex', '**.bib', '**.cls', '**.sty']
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Cache TeX Live packages
      id: cache
      uses: actions/cache@v4
      with:
        path: |
          /var/cache/apt/archives
          /usr/share/texlive
          /usr/bin/pdflatex
        key: texlive-apt-cache-v1
    
    - name: Install TeX Live
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        echo "Installing TeX Live (first time)..."
        
        # Update package list
        sudo apt-get update -qq
        
        # Install TeX Live packages
        sudo apt-get install -y \
          texlive-latex-base \
          texlive-latex-recommended \
          texlive-latex-extra \
          texlive-fonts-recommended
        
        echo "Installation completed!"
    
    - name: Verify TeX Live (from cache or fresh install)
      run: |
        echo "Verifying TeX Live installation..."
        which pdflatex
        pdflatex --version
        echo "TeX Live ready!"
    
    - name: Compile LaTeX
      run: |
        # Check if main.tex exists
        if [ ! -f "main.tex" ]; then
          echo "Error: main.tex not found!"
          exit 1
        fi
        
        echo "Compiling main.tex..."
        
        # Compile with error handling
        pdflatex -interaction=nonstopmode main.tex || true
        
        # Check if PDF was created
        if [ -f "main.pdf" ]; then
          echo "✅ Compilation successful!"
          ls -la main.pdf
        else
          echo "❌ Compilation failed - no PDF generated"
          cat main.log
          exit 1
        fi
    
    - name: Commit PDF
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "LaTeX Compiler"
        
        git add main.pdf
        
        if ! git diff --staged --quiet; then
          git commit -m "Auto-compile LaTeX: $(date '+%Y-%m-%d %H:%M:%S')"
          git push
          echo "PDF committed successfully!"
        else
          echo "No changes to commit"
        fi
