name: LaTeX Compiler

on:
  push:
    paths: ['**.tex', '**.bib', '**.cls', '**.sty']
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Cache TeX Live
      id: cache
      uses: actions/cache@v4
      with:
        path: /usr/local/texlive
        key: texlive-simple-v1
    
    - name: Install TeX Live
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        echo "Installing TeX Live..."
        
        # Use apt to install basic TeX Live (much simpler)
        sudo apt-get update
        sudo apt-get install -y texlive-latex-extra texlive-fonts-recommended texlive-science
        
        echo "TeX Live installation completed!"
    
    - name: Compile LaTeX
      run: |
        # Check if main.tex exists
        if [ ! -f "main.tex" ]; then
          echo "Error: main.tex not found!"
          exit 1
        fi
        
        echo "Compiling main.tex..."
        
        # Compile (run twice for references)
        pdflatex -interaction=nonstopmode main.tex
        pdflatex -interaction=nonstopmode main.tex
        
        echo "Compilation completed!"
        ls -la main.pdf
    
    - name: Commit PDF
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "LaTeX Compiler"
        
        git add main.pdf
        
        if ! git diff --staged --quiet; then
          git commit -m "Auto-compile LaTeX: $(date '+%Y-%m-%d %H:%M:%S')"
          git push
          echo "PDF committed successfully!"
        else
          echo "No changes to commit"
        fi
